name: Build dependencies for Ipe on MacOS
on: workflow_dispatch
jobs:
  Build:
    runs-on: macos-latest
    env:
      OSXTARGET: -mmacosx-version-min=12.00 -target arm64-apple-macos12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup
        run: make setup
      - name: Compile libpng
        run: make libpng
      - name: Compile lua
        run: echo make lua
      - name: Compile libspiro
        run: echo make spiro
      - name: Compile qhull
        run: make qhull
      - name: Compile GSL
        run: echo make gsl
      - name: View result
        run: ls -R osxlibs
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: ipe-osxlibs
          path: osxlibs
          retention-days: 2
      - run: 'echo "Status ${{ job.status }}"'
