name: Build dependencies for Ipe on MacOS
on: workflow_dispatch
jobs:
  Build:
    runs-on: macos-latest
    env:
      OSXTARGET: -mmacosx-version-min=10.10 -target x86_64-apple-macos10.10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup
        run: make setup
      - name: Compile libpng
        run: echo make libpng
      - name: Compile Freetype
        run: echo make freetype
      - name: Compile pixman
        run: echo make pixman
      - name: Compile Cairo
        run: echo make cairo
      - name: Compile lua
        run: make lua
      - name: Compile libspiro
        run: echo make spiro
      - name: Compile qhull
        run: echo make qhull
      - name: Compile GSL
        run: echo make gsl
      - name: View result
        run: ls -R osxlibs
      - name: Create archive
        run: tar czvf osxlibs-intel.tar.gz osxlibs
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: osxlibs-intel
          path: osxlibs-intel.tar.gz
          retention-days: 2
      - run: 'echo "Status ${{ job.status }}"'
